=== curiousabel/Password-Manager/Accounts.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:P="password" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import namespace="Password" />
  <xs:annotation>
    <xs:documentation xml:lang="en">
      password Managament System 
    </xs:documentation>
  </xs:annotation>
  
  <!--password Precentage-->
  <xs:simpleType name="precent">
    <xs:restriction base="xs:unsignedByte">
      <xs:minInclusive value="0"/>
      <xs:maxExclusive value="100"/>
    </xs:restriction>
  </xs:simpleType>
  
<!--password"Strength" -->
  <xs:simpleType name="strength">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Very Weak"/>
      <xs:enumeration value="Weak"/>
      <xs:enumeration value="Good"/>
      <xs:enumeration value="Strong"/>
      <xs:enumeration value="Very Strong"/>
    </xs:restriction>
  </xs:simpleType>
  

  
  <!-- Remove White Space -->
  <xs:simpleType name="whitespace">
    <xs:restriction base="xs:string">
      <xs:pattern value="\S*"/>
    </xs:restriction>
  </xs:simpleType>
  
  
  <!--Root the start of the xml -->
  <xs:element name="username">
    <!--Parent root start " Username "  -->
    <xs:complexType>
      <xs:sequence>
        <!-- child element of "Username" start  -->
        <xs:element name="accounts"  >
          <xs:complexType>
            <xs:sequence>
              <!--Child element of "accounts" start -->
              <xs:element name="account"  maxOccurs="unbounded">
                <xs:complexType>
                  <!--Child element of "account" start-->
                  <xs:sequence>
                    <xs:element name="description" maxOccurs="1" minOccurs="1" type="xs:string" />
                    <xs:element name="account-Number" maxOccurs="1" minOccurs="1" type="xs:string" />
                    <xs:element name="password-Date" type="xs:date" />
                    <xs:element name="password-Strength"  >
                      <xs:simpleType >
                        
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="very weak"/>
                          <xs:enumeration value="weak"/>
                          <xs:enumeration value="good"/>
                          <xs:enumeration value="strong"/>
                          <xs:enumeration value="very strong"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="password-percentage"  >
                      <xs:simpleType>
                        <xs:restriction base="xs:integer">
                          <xs:minInclusive value="0"/>
                          
                          <xs:maxInclusive value="100"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                   
                    <xs:element name="Login-urI" type="xs:string" minOccurs="0" maxOccurs="1" />
                  </xs:sequence>
                  <!--Child element of "account" Ends -->
                  <!--Attribute of "account" start -->
                  <xs:attribute name="UserId" type="whitespace" use="required" />
                  <xs:attribute name="password" type="whitespace" use="required"  />
              <!--Attribute of "account" End -->
                </xs:complexType>
                
              </xs:element>  <!--End Of "account" Element -->
            </xs:sequence>
          </xs:complexType>
          
        </xs:element>  <!--End Of "account" Element -->
      </xs:sequence>
      <!--Attribute for "Username" -->
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
    <!--Parent root End " Username "  -->
  </xs:element>
  <!--End og the xml -->
</xs:schema>

=== curiousabel/Password-Manager/Accounts.xml
<?xml version="1.0" encoding="utf-8"?>
<username name="Kobe" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Accounts.xsd">
  <accounts>
    <account UserId="K_booke@fanshaweonline.ca" password="Abc1234?">
      <description>Fanshawe Online Login </description>
      <account-Number>456789</account-Number>
      <password-Date>2008-01-10</password-Date>
      <password-Strength>weak</password-Strength>
      <password-percentage> 25</password-percentage>
      <Login-urI>https://www.fanshaweonline.ca</Login-urI>
    </account>
    <account UserId="K_booke@gmail.ca" password="Abc1234?">
      <description>Visual Studio </description>
      <account-Number>86152</account-Number>
      <password-Date>2014-01-23</password-Date>
      <password-Strength>strong</password-Strength>
      <password-percentage>98</password-percentage>
      <Login-urI>https://www.visualStudio.ca</Login-urI>
    </account>
    <account UserId="cav@gmail.ca" password="Abc1234?">
      <description>NBA Login</description>
      <account-Number>66457</account-Number>
      <password-Date>2018-12-02</password-Date>
      <password-Strength>strong</password-Strength>
      <password-percentage>45</password-percentage>
      <Login-urI>https://www.nba.ca</Login-urI>
    </account>
    <account UserId="baller@gmail.ca" password="Abc1234?">
      <description>Slam Magazine </description>
      <account-Number>66457</account-Number>
      <password-Date>2018-08-02</password-Date>
      <password-Strength>strong</password-Strength>
      <password-percentage>45</password-percentage>
      <Login-urI>https://www.SlamOnline.ca</Login-urI>
    </account>
    <account UserId="bobjohn@gmail.ca" password="Abc1234?">
      <description>Billing Co.</description>
      <account-Number>66457</account-Number>
      <password-Date>2018-12-02</password-Date>
      <password-Strength>strong</password-Strength>
      <password-percentage>45</password-percentage>
      <Login-urI>https://www.BillingCo.ca</Login-urI>
    </account>
    <account UserId="dfa" password="dsfad">
      <description>dhbfaewu</description>
      <account-Number>aad</account-Number>
      <password-Date>2018-05-29</password-Date>
      <password-Strength>very weak</password-Strength>
      <password-percentage>16</password-percentage>
      <Login-urI>dhbfaewu</Login-urI>
    </account>
    <account UserId="sddcs" password="scvdf">
      <description>dsd</description>
      <account-Number>dfvfd</account-Number>
      <password-Date>2018-05-29</password-Date>
      <password-Strength>very weak</password-Strength>
      <password-percentage>17</password-percentage>
      <Login-urI>dsd</Login-urI>
    </account>
  </accounts>
</username>

=== curiousabel/Password-Manager/BadAcount.xml
<?xml version="1.0" encoding="utf-8" ?>
<username name ="Kobe"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Accounts.xsd" >

  <accounts>
    <!--A string without embedded spaces "Password"  and the other one "userId"  with  other whitespace characters-->
    <account UserId=" " password="Abc 1234?">
      <description>Fanshawe Online Login </description>
      <account-Number >456789</account-Number>
      <!--date fromat is not the same should be 2008-10-29 -->
      <password-Date>2008/10/29</password-Date>
      <!--Not one of the choices -->
      <password-Strength >Vry eak</password-Strength>
      <!--less than 0 or Greater than 100 Dont work-->
      <password-percentage>-25</password-percentage>
      <!--More than one Login-Url-->
      <Login-urI>http://www.fanshaweonline.ca</Login-urI>
      <Login-urI>http://www.fanshaweonline.ca</Login-urI>
    </account>

  </accounts>
</username>
